### ISSUE TITLE
可能有插件冲突There may be plug-in conflicts

### ISSUE THREAD

**Issue by kunpeng9** [ijgnd/anki__preview_card_edit_note_in_extra_window_linked_from_reviewer#7]
也可能是其他的问题。There could be other problems.

错误 
有一个错误发生了.请在按住shift键的同时启动Anki，这样可以临时的禁用您已经安装的插件。 
如果仅仅是因为插件引起的问题，请选择工具>插件菜单项来将出错的的插件设置成失效，然后重启Anki，重复以上的步骤直到你发现了具体是哪个插件引起的问题。 
当你已经发现是因为插件引起的问题，请在我们的支持网站上 [插件支持](https://help.ankiweb.net/discussions/add-ons/) 上报告问题。 
调试信息：
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-12-07 11:01:25

Caught exception:
Traceback (most recent call last):
  File "google\protobuf\internal\python_message.py", line 702, in field_setter
  File "google\protobuf\internal\type_checkers.py", line 171, in CheckValue
TypeError: '1234567890123' has type <class 'str'>, but expected one of: (<class 'int'>,)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "google\protobuf\internal\python_message.py", line 558, in init
  File "google\protobuf\internal\python_message.py", line 704, in field_setter
TypeError: Cannot set BackendProto.CardID.cid to '1234567890123': '1234567890123' has type <class 'str'>, but expected one of: (<class 'int'>,)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\YEDONG\AppData\Roaming\Anki2\addons21\1423933177\exporter.py", line 79, in createReferencesInMedia
    txt = text_for_card(cid)
  File "C:\Users\YEDONG\AppData\Roaming\Anki2\addons21\1423933177\exporter.py", line 22, in text_for_card
    c = mw.col.getCard(cid)
  File "anki\collection.py", line 306, in getCard
  File "anki\cards.py", line 45, in __init__
  File "anki\cards.py", line 51, in load
  File "anki\rsbackend_gen.py", line 309, in get_card
  File "google\protobuf\internal\python_message.py", line 560, in init
  File "google\protobuf\internal\python_message.py", line 477, in _ReraiseTypeErrorWithFieldName
  File "six.py", line 695, in reraise
  File "google\protobuf\internal\python_message.py", line 558, in init
  File "google\protobuf\internal\python_message.py", line 704, in field_setter
TypeError: Cannot set BackendProto.CardID.cid to '1234567890123': '1234567890123' has type <class 'str'>, but expected one of: (<class 'int'>,) for field CardID.cid

**Comment by ijgnd** [comment]
Thanks for this report. It's just my add-on. I'll upload a fix in the next 24 hours to ankiweb.

I'm closing this issue now for my convenience. If the problem persists after updating (in two days) let me know and reopen this issue or make a new one.

In the meantime you can fix it for yourself if you add one line [here](https://github.com/ijgnd/anki__preview_card_edit_note_in_extra_window_linked_from_reviewer/blob/master/src/exporter.py#L21) with a text editor (like notepad.exe) and restart Anki.

from
   
    def text_for_card(cid):
        c = mw.col.getCard(cid)

to:

    def text_for_card(cid):
        cid = int(cid)
        c = mw.col.getCard(cid)

**Comment by ijgnd** [comment]
I was quite busy in the last days. I finally uploaded the new version. Could you update your add-ons, restart, and try again. If the problem persists let me know.
